server:
  port: 8080

spring:
  redis:
    host: 47.98.34.32
    #host: 172.16.109.74
log:
  home: /home/project/daily/log

#pingpp
pingpp:
    privateKey.path: /home/project/daily/pingpp_private_key.pem