server:
  port: 8080

spring:
  profiles:
    active: @profiles.active@
  datasource:
    url: jdbc:mysql://47.98.34.32:3306/pay?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: iK!%Qh0h7fg
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面数据源中
    # 初始化大小，最小，最大
    initialSize: 10
    minIdle: 10
    maxActive: 100
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    # ------------------------------DURID-------
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 30
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，wall用于防火墙
    filters: stat,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
    #使用非公平锁
    useUnfairLock: true
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: false
    validationQueryTimeout: 1
    keepAlive: true

  redis:
    host: 47.98.34.32
    port: 6379
    password: 31yCOhZBHpXV2doU
    jedis:
      pool:
        maxActive: 100
        maxIdle: 10


mybatis:
  mapper-locations: classpath:/mybaits/mapper/*.xml
  config-location: classpath:/mybatis/config/mybatis-config.xml
      
#pingpp
pingpp:
  appId: app_1afL4SKG0mfDPKav
  appKey: sk_test_nvnnH8GmvfrLbHyvXDC8q54O
  privateKey.path: /Users/chenyaozong/migu/projects/pingpp/src/main/resources/pingpp_private_key.pem
